---
- name: Add nodejs key
  become_user: root
  ansible.builtin.apt_key:
    url: https://deb.nodesource.com/gpgkey/nodesource.gpg.key
    id: 9FD3B784BC1C6FC31A8A0A1C1655A0AB68576280
    state: present

- name: Add nodejs repo
  become_user: root
  ansible.builtin.apt_repository:
    repo: "deb https://deb.nodesource.com/node_{{ node_version | default(16) }}.x focal main"
    state: present
    update_cache: yes

- name: Install the nodejs
  become_user: root
  ansible.builtin.apt:
    name: nodejs
    state: present

- name: Install http-server
  become_user: root
  ansible.builtin.npm:
    name: http-server
    global: yes


- name: Add frontend service user
  become_user: root
  ansible.builtin.user:
    name: "{{ frontend_user }}"
    create_home: no
    shell: /sbin/nologin

- name: Create directory for log
  become_user: root
  ansible.builtin.file:
    path: "{{ frontend_path }}/logs"
    state: directory

- name: Download frontend artifact from nexus
  become_user: root
  ansible.builtin.get_url:
    url: "{{ nexus_url }}/sausage-store-zasypkin-nikita-frontend/sausage-store-front/{{ frontend_version }}/sausage-store-{{ frontend_version }}.tar.gz"
    dest: "{{ frontend_path }}"
    username: "{{ nexus_user }}"
    password: "{{ nexus_password }}"
    timeout: 5

- name: Unarchive artifact frontend
  become_user: root
  ansible.builtin.unarchive:
    src: "/var/www-data/dist/sausage-store-{{ frontend_version }}.tar.gz"
    dest: "{{ frontend_path }}"
    copy: no

- name: Add permissions
  become_user: root
  ansible.builtin.file:
    path: "{{ frontend_path }}"
    owner: "{{ frontend_user }}"
    group: "{{ frontend_user }}"
    recurse: yes
    mode: '0755'

- name: Copy unit-file on server
  become_user: root
  ansible.builtin.template:
    src: sausage-store-frontend.service.j2
    dest: /etc/systemd/system/sausage-store-frontend.service
  notify:
    - Re-reading the configuration systemd
    - Restart frontend
