---
- name: Re-reading the configuration systemd
  ansible.builtin.systemd:
    daemon_reload: true

- name: Restart frontend
  become_user: root
  ansible.builtin.service:
    name: sausage-store-frontend
    state: restarted
    enabled: true